package com.gym.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Date;

@Data
@Document(collection = "members")
public class Member {
    @Id
    private String id; // Auto-generated by MongoDB

    private String memberName;
    private String mobile;
    private String email;
    private String address;
    private Date joiningDate;
    private Date dateOfBirth;
    private Date selectBatch; // Optional
    private String panCard; // Optional
    private String adharCard; // Optional
    private String membershipPlan; // Optional
}
